spring:
  application:
    name: Api-Gateway

  profiles:
    active: dev

  security:
    user:
     name: "bilal"
     password: "bilal"



  cloud:
    gateway:
      routes:
        - id: Key-Clock-Admin-Client
          uri: http://bilal:8083/actuator/info
          predicates:
            - Path=/uaa/**
        - id: Question-Service
          uri: http://bilal:8082/actuator/info
          predicates:
            - Path=/questions/**
