spring:
  application:
    name: CONFIG-SERVER-Default
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  # eureka:
  #   client:
  #     serviceUrl:
  #       defaultZone: http://localhost:8761/eureka/

# keycloak:
#   credentials:
#     secret: yQPTw1vFTwD9rCoy3BQAvvQ8QLpU1KUH
#   realm: springBootKeyclock
#   client: my_client
#   auth-server-url: http://localhost:8080
#   ssl-required: external
#   resource: cai-uaa
#   bearer-only: true
#   cors: true
#   public-client: true
#   connection-pool-size: 10        
