spring:
  datasource:
    url: jdbc:mysql://localhost:3306/question_db?createDatabaseIfNotExist=true
    username: root
    password: admin

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/springBootKeyclock

